### PR TITLE
Re-enable OKD left navigation

### PR DESCRIPTION
**Pull request by mareklibra**
The default landing page is stil "Virtual Machines" (instead of "Home").

Except:
- service catalog
- Operator Lifecycle Management
- Builds
- Administration

### CODE REVIEW

**Comment by mareklibra** [comment]
okdvirtleftsidenav

**Comment by mareklibra** [comment]
Please note: the screenshot above was taken from my dev environment. When properly deployed, there will be the console-selection dropdown available in addition.

**Comment by mareklibra** [comment]
Good point :-) Would it make sense to postpone this decision to the point when we are actually merging our stuff to the upstream?

@lizsurette , is this PR good-to-go for now from your perspective?

**Comment by mareklibra** [comment]
Linter issues fixed.

**Comment by jelkosz** [comment]
@mareklibra I agree the virtual machines will not end up on the first place ultimately so we will need to agree with the core openshift team on the positioning. For now I would leave it on the first place, and change it later when we will get to some agreement. But would not block this PR on it

**Comment by rawagner** [comment]
LGTM, lets address  the positioning issue as follow-up

**Pull request merged**
