### PR TITLE
Metalkube baremetal host detail page

### PR DESCRIPTION
**Pull request by honza**
A small PR on purpose to make code review easier. I'll work on the other tabs in subsequent PRs.

screenshot from 2019-03-04 16-20-54

### CODE REVIEW

**Comment by lizsurette** [comment]
Great to see this! I think we want to change the name from "Hosts" to "Bare Metal Hosts". @andybraren can confirm if I'm just making things up, though :)

Also, just a heads up that OCP 4.0 will end up pulling Machines and Nodes into the "Compute" section and we should follow this pattern and add Bare Metal Hosts as well. Here is what it will look like for OCP 4.0:
nodes-compact

**Comment by andybraren** [comment]
@lizsurette Speaks the truth - hopefully renaming to "Bare Metal Hosts" will reduce some confusion. I'll update our Day 2 screens with the latest nav.

**Comment by honza** [comment]
That's trivial to change, thanks for the heads up. It's actually in @jtomasek's PR.

I noticed in the wireframes that the overview is styled as a card. This doesn't seem to match the rest of the detail pages (pods, projects, etc). Is that on purpose? In this PR, I followed the general convention.

**Comment by jtomasek** [comment]
> That's trivial to change, thanks for the heads up. It's actually in @jtomasek's PR.
> 
> I noticed in the wireframes that the overview is styled as a card. This doesn't seem to match the rest of the detail pages (pods, projects, etc). Is that on purpose? In this PR, I followed the general convention.

I think following the convention for now is good enough for the initial patch. We can iterate later once we settle on the general cluster dashboard and reuse components in host detail overview.

I'll update my PR with new 'Bare Metal Hosts' title/label. @andybraren Is that for all the labels or just the menu item? I assume that all labels should get changed, right?

**Comment by lizsurette** [comment]
> I think following the convention for now is good enough for the initial patch. We can iterate later once we settle on the general cluster dashboard and reuse components in host detail overview.

+1 The Cluster Dashboard may influence where we go with the Host Overview along with other overviews (Pod, Node, Storage Class, PV, PVC) but we will need to figure out a strategy there and it's quite out of the scope for this, so keep doing what you are doing!

> I'll update my PR with new 'Bare Metal Hosts' title/label. @andybraren Is that for all the labels or just the menu item? I assume that all labels should get changed, right?
Thanks @jtomasek ! I'd vote for changing it everywhere to be consistent but will let @andybraren have the final say from UX :)

**Comment by andybraren** [comment]
^ @honza What @lizsurette said. We have meetings coming up to figure out how to make things consistent OpenShift-wide again, but for MetalKube's purposes the new card-based Overview page is very intentional. Iterating on this initial patch sounds great, and we're trying to solidify those Dashboard cards as soon as we can. Feedback welcome!

**Comment by andybraren** [comment]
Good question @jtomasek. My first thought (and hope) is to only change:

1. The menu item from "Hosts" to "Bare Metal Hosts"
2. The name of the resource from "Host" to "Bare Metal Host" (with a blue "BMH" badge)

I'd like to try to keep the "Add Host' button the same and refer to these as "hosts" in modals, action kebab popovers, and anywhere else. Hopefully this doesn't confuse people more, but if it does then we may need to change those too.

I'm resuming work on Day 2 areas other than the Dashboard now and will play around with this.

**Comment by honza** [comment]
Rebased on top of master

**Comment by mareklibra** [comment]
LGTM, let's take this as a base for next iterations.
Thanks for smaller PRs but with relevant features :-)

**Pull request merged**
