### PR TITLE
Upgrade @patternfly/react-console to the latest

### PR DESCRIPTION
**Pull request by mareklibra**

### CODE REVIEW

**Comment by rawagner** [comment]
@mareklibra CI is failing

**Comment by mareklibra** [comment]
pf-react changed structure of dist modules (https://github.com/patternfly/patternfly-react/commit/1f3411a6e708e833e48921380ae736cf5f79862b).
References needs to be fixed in pf-raect first: https://github.com/patternfly/patternfly-react/pull/894

**Comment by mareklibra** [comment]
Example:
```
in 1.4.6: import { EmptyState, Button, noop } from 'patternfly-react';
in 1.5.6: import noop from 'patternfly-react/dist/esm/components/noop/noop';
in sources: import { EmptyState, Button, noop } from 'patternfly-react';
```

**Comment by mareklibra** [comment]
Replaced by #104

**Pull request closed without merging**
