### PR TITLE
Lower logo font size

### PR DESCRIPTION
**Pull request by rawagner**
https://bugzilla.redhat.com/show_bug.cgi?id=1667815
logo_size

### CODE REVIEW

**Comment by mareklibra** [comment]
@matthewcarleton, wdyt?

**Comment by matthewcarleton** [comment]
This is something I've talked to Patrick about. It seems like this is a css issue. They way the layout is built that logo shouldn't be able to stretch outside it's container like that. I'll follow up with Patrick about this today. Thanks!

**Comment by priley86** [comment]
it looks like the pf4 base resets where disabled in this upstream commit:
https://github.com/openshift/console/commit/02ba4c7dda385bd41f88efc565b7dbf932c4b2c4#diff-6dbc2aec46416806ac17a0975691677f

although, i'm not entirely sure why. Would have to ask @rhamilto. My guess is logo sizing was not ideal at the time (but we can revisit this in future beta releases of PF). 

For now, I would suggest sizing it smaller to match PF standard. We can also revisit the SVG and properly brand the text ("Viritualization") later too.
https://github.com/priley86/web-ui/commit/3cbdd505cb668dd7da41d8aaf49837d3a1dcdf1e

screen shot 2019-01-21 at 11 59 02 am

**Comment by priley86** [comment]
thanks @rhamilto - we can revisit w/ @matthewcarleton again soon.

**Comment by maryshak1996** [comment]
@rhamilto hey! I believe that I provide design specs for this a while ago, and some layout/sizing for PF4 has since changed. I'm guessing that this might be where some confusion is coming into play - but I'd be happy to chat with anyone if you need any other design guidance :)

**Comment by mareklibra** [comment]
As 1.4 release is getting close, let's merge this as a workaround and fix properly later.

**Pull request merged**
