### PR TITLE
consoles: add spinner when VM is starting

### PR DESCRIPTION
**Pull request by mareklibra**
The spinner is implemented as "loading dots" to be alligned with
the rest of the application.

Fixes: https://github.com/kubevirt/web-ui/issues/45

### CODE REVIEW

**Comment by mareklibra** [comment]
01_starting
---
02_down

**Comment by mareklibra** [comment]
cc @yfrimanm , @lizsurette

**Comment by lizsurette** [comment]
Looks nice, @mareklibra! Would it be tough to add a link at the end of "This Virtual Machine is down. Please start it to access its console.  [Start Virtual Machine](url)" ?

**Comment by mareklibra** [comment]
@liz, here we go: 

---

**Comment by yfrimanm** [comment]
Or maybe something like this?
[image: image.png]

**Comment by lizsurette** [comment]
> Or maybe something like this?

@yfrimanm I don't see an attachment here...

**Comment by yfrimanm** [comment]
I copied a screen shot but somehow it didn't work out, sorry about that.
[image: Screenshot01.png]

**Comment by lizsurette** [comment]
> I copied a screen shot but somehow it didn't work out, sorry about that.

Hmm still didn't work...maybe because you are trying to attach via email? Try opening up in GitHub and reply instead?

**Comment by yfrimanm** [comment]
Or maybe like this?
screenshot01

**Comment by lizsurette** [comment]
> Or maybe like this?

Ah yes, this is nice to work it right into the message! @mareklibra what do you think?

**Comment by mareklibra** [comment]
This looks much more smooth. It will be a little bit harder to internationalize one day, but it's not an issue for today :-)

**Pull request merged**
