### PR TITLE
Improve VM Status

### PR DESCRIPTION
**Pull request by mareklibra**
VM Status is newly more fine-grained and is rendered with an icon.

Error states are farther enriched for
- links to appropriate 'events' page
- "tooltip" info about the issue

Fixes: https://github.com/kubevirt/web-ui/issues/77
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1649826
Requires: ~~https://github.com/kubevirt/web-ui-components/pull/108~~

### CODE REVIEW

**Comment by mareklibra** [comment]
vmstatus

**Comment by rawagner** [comment]
This a good chance to merge Status and Phase columns imo.

**Comment by mareklibra** [comment]
> This a good chance to merge Status and Phase columns imo.

Good point. Assuming the new state mapping works correctly, we can remove the `Phase` column.

**Comment by mareklibra** [comment]
Cc @lizsurette , @andybraren

**Comment by andybraren** [comment]
Agreed - I'm not quite sure what "Phase" refers to, but it seems close enough to State that they could be merged.

Let me know if you think there should be any other statuses in addition to Running, Off, Error, Cloning, and Warning shown in #77.

**Comment by mareklibra** [comment]
The `Phase` column is removed.
Screenshot above is updated.

**Comment by mareklibra** [comment]
> Let me know if you think there should be any other statuses in addition to Running, Off, Error, Cloning, and Warning shown in #77

I splitted  the `Error` to `VM Error` and `Pod Error`. The first one refers to issues with VM definition, the later one with scheduling or image download. The user is navigated to corresponding (vm vs. pod) `Events` detail page accordingly.

**Comment by andybraren** [comment]
@mareklibra Ah, I can see why the two categories are different. That makes sense.

Since users (hopefully) aren't _always_ going to have many VMs with errors, I think having one "Error" filter that includes "VM Error" and "Pod Error" text variants in the Status column could make sense. How does the below look to you?

1-1-warning

**Comment by ohadlevy** [comment]
just wondering, what happens with long vm names? (or any other long text attribute)

**Comment by andybraren** [comment]
@ohadlevy I don’t have an easily shareable link to an example at the moment, but the intent is for a “...” ellipsis achieved in CSS using `overflow: hidden` and `text-overflow: ellipsis`. This would be a flexible solution that would work even if/when we allow users to add/remove columns in the future.

Each table value should probably also include a `title` attribute so that the full string appears in hover.

**Comment by ohadlevy** [comment]
ack, foreman project wrote this https://github.com/amirfefer/react-ellipsis-with-tooltip npm package which i believe is what you had in mind.

**Comment by mareklibra** [comment]
Thanks for these hints, I can open a pull request to openshift/console project to do that generically.

**Comment by mareklibra** [comment]
@andybraren , I had to reduce the count of filters to just following:
- Running
- Off
- Other

The last one groups all the remaining statuses like migration, import or error.

The `Status` column still shows detailed value, including tooltip or link to a related object (like VM events or one of the failing pods).

It would be quite complicated to allow filtering on all specific values since we would need to analyse related objects to determine the status. And these objects are not available for the filter, just the `VM` object can be used recently.

Enhancing this core OKD feature is possible but pretty complex. I even can't say if maintainers will be happy with this change. 
So if more accurate filters are needed, I would implement that in a separate PR/issue.

Please let me know if you are ok with that.

**Comment by mareklibra** [comment]
status

**Comment by mareklibra** [comment]
required web-ui-components changes released within v0.1.9

**Comment by andybraren** [comment]
@mareklibra The other filters would be useful but I understand that we should avoid the technical complexity, especially if they would make the maintainers unhappy. Glad the new Status improvements are merged. 👍

**Pull request merged**
